---
efiBootLoader: "grub"

grubInstall: "grub-install"
grubMkconfig: "grub-mkconfig"
grubCfg: "/boot/grub/grub.cfg"

grubProbe: "grub-probe"
efiBootMgr: "efibootmgr"

efiBootloaderId: "Galapagos"
installEFIFallback: true
installHybridGRUB: false
