---
displaymanagers:
  - lightdm
  - sddm
  - gdm

basicSetup: false
sysconfigSetup: false

lightdm:
  preferred_greeters:
    - lightdm-gtk-greeter.desktop

sddm:
  configuration_file: "/etc/sddm.conf"
