---
mode: required
method: legacy

default: cinnamon

labels:
  step: "Masaüstü Ortamı"

items:

- id: cinnamon
  name: "Cinnamon"
  description: "Galapagos Linux için Cinnamon masaüstü ortamı."
  screenshot: "/etc/calamares/branding/galapagos/cinnamon.png"

- id: kde
  name: "KDE Plasma"
  description: "Galapagos Linux için KDE Plasma masaüstü ortamı."
  screenshot: "/etc/calamares/branding/galapagos/kde.png"

- id: gnome
  name: "GNOME"
  description: "Galapagos Linux için GNOME masaüstü ortamı."
  screenshot: "/etc/calamares/branding/galapagos/gnome.png"
