---
dontChroot: true
timeout: 30
script:
    - command: "if [ -f \"${ROOT}/etc/apt/sources.list.d/cdrom.sources\" ]; then rm -f \"${ROOT}/etc/apt/sources.list.d/cdrom.sources\"; fi"
    - command: "if mountpoint -q \"${ROOT}/cdrom\"; then umount \"${ROOT}/cdrom\" || true; fi"
    - command: "if [ -d \"${ROOT}/cdrom\" ]; then rmdir \"${ROOT}/cdrom\" 2>/dev/null || true; fi"
