[Project]
cubic_version = 2026.09.110-release~202609120048~ubuntu26.04.1
first_version = 2026.09.110-release~202609120048~ubuntu26.04.1
create_date = 2026-09-26 17:53
modify_date = 2026-09-26 17:57
directory = /home/vboxuser/galapagos

[Original]
iso_file_name = ubuntu-26.04-desktop-amd64.iso
iso_directory = /home/vboxuser/İndirilenler
iso_volume_id = Ubuntu 26.04 amd64
iso_release_name = Resolute Raccoon
iso_disk_name = 

[Custom]
iso_version_number = 1.0.0
iso_file_name = galapagos-linux-1.0.0-amd64.iso
iso_directory = /home/vboxuser/galapagos
iso_volume_id = GALAPAGOS_1_0
iso_release_name = Galapagos Linux
iso_disk_name = Galapagos Linux 1.0

[Layout]
casper_directory = casper
squashfs_directory = casper
squashfs_file_name = 
manifest_file_name = filesystem.manifest
minimal_remove_file_name = 
standard_remove_file_name = 
size_file_name = filesystem.size
minimal_squashfs_file_name = minimal.squashfs
minimal_manifest_file_name = minimal.manifest
minimal_size_file_name = minimal.size
standard_squashfs_file_name = minimal.standard.squashfs
standard_manifest_file_name = minimal.standard.manifest
standard_size_file_name = minimal.standard.size
install_sources_file_name = install-sources.yaml
live_squashfs_file_name = minimal.standard.live.squashfs
live_manifest_file_name = minimal.standard.live.manifest
live_size_file_name = minimal.standard.live.size
live_generic_squashfs_file_name = 
live_generic_manifest_file_name = 
live_generic_size_file_name = 

[Status]
is_success_analyze = True
is_success_copy = True
is_success_extract = True
iso_template = 789C8D51CD8E832010BEFB14DCBCEC54C5D6AA0FB25732C06848500CD0266DD3775FFFB6E9269BEC1E20F00DCCF733F0C9D2C7D5D9CB40C2E8679A00F4FE22390CD233003346F257B4AD750AADE8429B07284EA1BD9377627E33C58FF5D84FB14D1FD2B928CC803D096D3CA9E8FCED994DE8A389C68D501CCCD02F1C9377712E9B2BC110B40B6051924DE0F554A89B15684D3F32D775EF85F91A28B2A29ADBCC02A0735E112CCC282D2580D344A316AF0F8C335E9F4B8EAA28BAAED6BC28241E659E63AE9A92E6257F37AAA1C87973D2ED3F8CF1DDD8464E1BBDC0B0E49280096B561B186F1331E498EB9C249D645396C7637D567955CB4A9E79D534EA9C806269B6B01E1446B46E692E77285B269499B2AE605219D9598C896E57303AA0E162D740927507EB5043307762C71D3163E760CF6B9FF70B4FE0BB23A08D7B1F62E95B463F5C6E53E12D5A3B27F5878025D12AF902C2C9D85C
iso_checksum = 
iso_checksum_file_name = 

[Options]
update_os_release = True
has_minimal_install = False
boot_configurations = 
compression = gzip

