---
modules-search: [ local ]

instances:
- id: desktop
  module: packagechooser
  config: packagechooser_desktop.conf

- id: installtype
  module: packagechooser
  config: packagechooser_installtype.conf

sequence:
- show:
  - welcome
  - locale
  - keyboard
  - packagechooser@desktop
  - packagechooser@installtype
  - partition
  - users
  - summary

- exec:
  - partition
  - mount
  - unpackfs
  - machineid
  - fstab
  - locale
  - keyboard
  - localecfg
  - users
  - networkcfg
  - hwclock
  - initramfscfg
  - initramfs
  - grubcfg
  - bootloader
  - galapagos-desktop
  - packages
  - displaymanager
  - umount

- show:
  - finished

branding: galapagos

prompt-install: true
dont-chroot: false
oem-setup: false
disable-cancel: false
disable-cancel-during-exec: false
hide-back-and-next-during-exec: true